
CREATE TABLE USUARIO (
NICK VARCHAR(50) PRIMARY KEY,
NOMBRE VARCHAR(9) ,
VISITAS INTEGER,
PASSWORD VARCHAR(50),
APELLIDOS VARCHAR(50),
EMAIL VARCHAR(50) ,
LOCALIDAD VARCHAR(50)
);

CREATE TABLE ARTICULO (
IDARTICULO VARCHAR(20) PRIMARY KEY,
NICK VARCHAR(50),
PRECIO REAL,
ESTADOARTICULO CHAR,
DESCRIPCION VARCHAR(50),
FOREIGN KEY (NICK) REFERENCES USUARIO(NICK)
);

